a = {"URL": "",
     "Collections": "",
     "Name": "",
     "Description": "",
     "Product Reference": "",
     "Pricing": "",
     "MATERIAL": "",
     "GEM-SETTING": "",
     "DIMENSIONS": "",
     "HEIGHT": "",
     "CASEBACK": "",
     "WATER-RESISTANCE (BAR)": "",
     "TYPE": "",
     "CALIBER": "",
     "FUNCTIONS": "",
     "COMPOSITION": "",
     "GEM-SETTING": "",
     "MATERIAL": "",
     "GEM-SETTING": "",
     "BUCKLE": "",
     "TOTAL GEM-SETTING": "",
     "MÉTIER D'ART": "",
     "LIMITED EDITION": "",
     "Add on": "",
     "img 1": "",
     "img 2": "", }
